### ISSUE TITLE
[FIX] notification 테이블 생성 오류 수정

### ISSUE THREAD

**Issue by kimwanyoung** [6-plus/6-plus-backend#40]
### 담당자
- 김완영

## 오류 내용
- draw 테이블 생성 이전에 notification 테이블을 생성하여, 외래키 참조 오류가 발생

## 해결 내용
- schema.sql 파일에서 draw테이블 생성과 notification생성 순서 바꿔줌

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the order of table creation in schema.sql to create the draw table before the notification table, resolving the foreign key reference error.

You can review changes in this commit: https://github.com/lkilu6456546/6-plus-6-plus-backend-40/commit/e5212877f3ba1d1a6e0ab2822d3f6de74a791ea4.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
